name: Portfolio page test, build and deploy

on:
  push:
    paths-ignore:
      - ".github/workflows/*.yaml"
      - "!.github/workflows/hosting.yaml"
      - "*.md"
      - ".gitignore"

jobs:
  Test:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: |
          npm ci
          cd functions/
          npm ci
          cd ..
      - name: Include firebase
        run: npm i -g firebase-tools
      - name: Set default firebase project
        env:
          DEFAULT_PROJECT: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use --add "$DEFAULT_PROJECT" --token "$FIREBASE_TOKEN"
      - name: Run test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run dev:emulator
          wait-on: "http://localhost:4000, http://localhost:8080"
          command: npm run cy:run

  Build:
    if: github.ref == 'refs/heads/master'
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the static files
        env:
          VUE_APP_GITHUB_USERNAME: ${{ secrets.VUE_APP_GITHUB_USERNAME }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSENGER_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSENGER_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
        run: CI=false npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: production-artifact
          path: dist

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: production-artifact
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID}}
        with:
          args: deploy --only hosting
