name: Portfolio deploy
on:
  push:
    paths-ignore:
      - "functions/**"
      - "security-rules/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/hosting.yaml"
      - "*.md"
      - ".gitignore"
    branches:
      - master
jobs:
  firebase-hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build the static files
        env:
          VUE_APP_GITHUB_USERNAME: ${{ secrets.VUE_APP_GITHUB_USERNAME }}
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
          VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.VUE_APP_FIREBASE_DATABASE_URL }}
          VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
          VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGE_BUCKET }}
          VUE_APP_FIREBASE_MESSENGER_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSENGER_SENDER_ID }}
          VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
        run: |
          npm ci
          CI=false npm run build
      - name: Deploy
        if: ${{ success() }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID}}
